[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "proj-gw-likelihood"
authors = [{name = "Stegmann", email = "jstegmann@mpa-garching.mpg.de"}]
dynamic = ["version", "description"]
